Repository Daemon-Technologies/Mining-Bot, pull requests merged in 2020-12, with the labels that each got.

#65 Add Mining Block Info
  src/pages/client/component/AccountForm.tsx
  src/pages/client/index.tsx
  src/pages/client/locales/zh-CN.ts
  src/pages/publicData/index.tsx
  src/services/client/Client.ts
  src/services/client/data.d.ts
  src/services/constants.ts
Labels: Alpha, enhancement

#70 [Sher] fix wallet bugs and optimize code
  src/pages/client/component/AccountForm.tsx
  src/pages/client/index.tsx
  src/pages/client/locales/zh-CN.ts
  src/pages/publicData/index.tsx
  src/pages/wallet/components/CreateForm.tsx
  src/pages/wallet/components/UpdateForm.tsx
  src/pages/wallet/index.tsx
  src/pages/wallet/service.ts
  src/services/API.d.ts
  src/services/client/Client.ts
  src/services/client/data.d.ts
  src/services/constants.ts
  src/services/login.ts
  src/services/publicdata/chainInfo.ts
  src/services/publicdata/data.d.ts
  src/services/wallet/accountData.ts
  src/services/wallet/faucet.ts
Labels: Alpha, bug

#84 download file feature & DNS constant
  package.json
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
  src/services/client/Client.ts
  src/services/client/socket.ts
  src/services/constants.ts
Labels: Alpha, bug, enhancement

#85 fix download loading & error message
  src/pages/client/index.tsx
  src/services/client/socket.ts
Labels: Alpha, bug, enhancement

#87 master merge dev
  package.json
  src/pages/client/component/AccountForm.tsx
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
  src/services/client/Client.ts
  src/services/client/data.d.ts
  src/services/client/socket.ts
  src/services/constants.ts
Labels: Alpha, bug, enhancement

#88 add downloading node status & fixing stx faucet issue.
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
  src/pages/wallet/index.tsx
Labels: Alpha, bug

#93 fix stop mining bot logic issue & fix min burn-fee issue
  README.md
  a.png
  src/pages/client/component/AccountForm.tsx
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
Labels: Alpha, bug

#96 fix fix stop mining bot logic issue & modify min burn-fee to 11000
  README.md
  a.png
  src/pages/client/component/AccountForm.tsx
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
  src/pages/wallet/index.tsx
  src/services/constants.ts
Labels: Alpha, bug

#101 Divide client module into small modules
  src/pages/client/component/AccountForm.tsx
  src/pages/client/component/ChainSyncInfoTable.tsx
  src/pages/client/component/MinerInfoTable.tsx
  src/pages/client/component/MiningInfoTable.tsx
  src/pages/client/component/OperationBoard.tsx
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/models/chainSyncInfo.ts
  src/pages/client/models/minerInfo.ts
  src/pages/client/models/miningInfo.ts
  src/pages/client/models/operationBoard.ts
  src/services/constants.ts
  src/services/locale.ts
Labels: Beta, enhancement, xenon

#102 [Sher] Divide pulbicData into small modules
  src/pages/client/index.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
  src/pages/client/models/operationBoard.ts
  src/pages/publicData/component/BlockInfoTable.tsx
  src/pages/publicData/component/ChainInfoTable.tsx
  src/pages/publicData/component/MinerInfoTable.tsx
  src/pages/publicData/component/MiningInfoTable.tsx
  src/pages/publicData/component/TokenPriceInfoTable.tsx
  src/pages/publicData/index.tsx
  src/pages/publicData/locales/en-US.ts
  src/pages/publicData/locales/zh-CN.ts
  src/pages/publicData/models/minerInfo.ts
  src/pages/publicData/models/miningInfo.ts
  src/services/client/Client.ts
  src/services/client/data.d.ts
  src/services/publicdata/chainInfo.ts
  src/services/publicdata/data.d.ts
  src/services/publicdata/miningInfo.ts
Labels: Beta, xenon
