Repository Daemon-Technologies/Mining-Bot, pull requests merged in 2021-01, with the labels that each got.

#108 [Sher] Add request timeout & Add Export function
  config/config.ts
  package.json
  src/access.ts
  src/pages/publicData/component/MinerInfoTable.tsx
  src/pages/publicData/component/MiningInfoTable.tsx
  src/pages/publicData/locales/en-US.ts
  src/pages/publicData/locales/zh-CN.ts
  src/pages/publicData/models/minerInfo.ts
  src/pages/publicData/models/miningInfo.ts
  src/pages/user/login/index.tsx
  src/services/publicdata/exportUtils.ts
  src/services/wallet/account.ts
Labels: Beta, enhancement, xenon

#111 Feature: Add NodeList
  src/pages/sysConf/index.tsx
  src/pages/sysConf/models/sysConf.ts
  src/services/sysConf/conf.ts
Labels: Beta, xenon

#112 [Sher] modify sysConfiguration and add Step3 for startMining
  src/pages/client/component/AccountForm.tsx
  src/pages/client/component/OperationBoard.tsx
  src/pages/client/models/nodeList.ts
  src/pages/client/models/operationBoard.ts
  src/pages/sysConf/index.tsx
  src/services/client/Client.ts
  src/services/constants.ts
  src/services/publicdata/chainInfo.ts
  src/services/sysConf/conf.ts
  src/services/wallet/account.ts
Labels: Beta, xenon

#113 fix issues related to wallet and client module
  src/pages/client/component/AccountForm.tsx
  src/pages/client/component/ChainSyncInfoTable.tsx
  src/pages/wallet/components/walletTable.tsx
  src/services/constants.ts
  src/services/publicdata/chainInfo.ts
  src/services/wallet/account.ts
Labels: Beta, bug, xenon

#114 Modify SysConf and Client/StartMining
  src/pages/client/component/AccountForm.tsx
  src/pages/client/component/AuthCode.tsx
  src/pages/client/component/OperationBoard.tsx
  src/pages/client/component/Step1AccountContent.tsx
  src/pages/client/component/Step2BurnFeeContent.tsx
  src/pages/client/component/Step3NodeInfoContent.tsx
  src/pages/client/locales/en-US.ts
  src/pages/client/locales/zh-CN.ts
  src/pages/publicData/component/BlockInfoTable.tsx
  src/pages/sysConf/index.tsx
  src/services/client/Client.ts
  src/services/client/socket.ts
  src/services/publicdata/chainInfo.ts
  src/services/sysConf/conf.ts
  src/services/sysConf/data.d.ts
Labels: Beta, xenon

#116 [Sher] fix bug: duplicated form name in system configuration
  src/pages/client/component/AuthCode.tsx
  src/pages/sysConf/index.tsx
  src/services/client/Client.ts
  src/services/sysConf/conf.ts
Labels: Beta, xenon

#117 Mining-Bot url connection issue.
  src/pages/client/component/AuthCode.tsx
  src/pages/sysConf/index.tsx
  src/services/client/Client.ts
  src/services/sysConf/conf.ts
Labels: Beta, xenon

#118 [Sher] Support Mainnet
  src/components/RightContent/SwitchNetwork.tsx
  src/pages/client/component/AccountForm.tsx
  src/pages/client/component/AuthCode.tsx
  src/pages/client/component/OperationBoard.tsx
  src/pages/client/component/Step2BurnFeeContent.tsx
  src/pages/client/models/operationBoard.ts
  src/pages/sysConf/index.tsx
  src/pages/wallet/components/walletTable.tsx
  src/services/client/Client.ts
  src/services/constants.ts
  src/services/publicdata/chainInfo.ts
  src/services/sysConf/conf.ts
  src/services/wallet/account.ts
  src/services/wallet/key.ts
  src/utils/utils.ts
Labels: Beta, mainnet
